# Protocol Configuration

[protocol]
dao = "0x145E9Ee481Bb885A49E1fF4c1166222587D61916"

# Liquidity Pools
BasePool = "0x19da41A2ccd0792b9b674777E72447903FE29074"

referralCode = "0x5055505045540000000000000000000000000000000000000000000000000000"

# GMX V2 core contracts (Arbitrum)
[gmx]
exchangeRouter = "0x1C3fa76e6E1088bCE750f23a5BFcffa1efEF6A41"
orderVault = "0x31eF83a530Fde1B38EE9A18093A333D8Bbbc40D5"
router = "0x7452c558d45f8afC8c83dAe62C3f8A5BE19c71f6"
reader = "0x470fbC46bcC0f16532691Df360A07d8Bf5ee0789"
oracle = "0xa11B501c2dd83Acd29F6727570f2502FAaa617F2"
dataStore = "0xFD70de6b91282D8017aA4E741e9Ae325CAb992d8"
orderHandler = "0xe68CAAACdf6439628DFD2fe624847602991A31eB"
orderHandlerGassless = "0xfc9Bc118fdDb89FF6fF720840446D73478dE4153"
liquidationHandler = "0xdAb9bA9e3a301CCb353f18B4C8542BA2149E4010"
adlHandler = "0x9242FbED25700e82aE26ae319BCf68E9C508451c"
referralStorage = "0xe6fab3F0c7199b0d34d7FbE83394fc0e0D06e99d"
ethUsdcMarket = "0x5615dEB798BB3E4dFa0139dFa1b3D433Cc23b72f"
chainlinkPriceFeedProvider = "0x527FB0bCfF63C47761039bB386cFE181A92a4701"

# Token addresses per chain
[arbitrum.token]
USDC = "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"
USDT = "0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9"
DAI = "0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1"
WETH = "0x82aF49447D8a07e3bd95BD0d56f35241523fBab1"
WBTC = "0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f"

[base.token]
USDC = "0x833589fcd6edb6e08f4c7c32d4f71b54bda02913"
USDT = "0xfde4C96c8593536E31F229EA8f37b2ADa2699bb2"
DAI = "0x50c5725949A6F0c72E6C4a641F24049A917DB0Cb"
WETH = "0x4200000000000000000000000000000000000006"
WBTC = "0x0555E30da8f98308EdB960aa94C0Db47230d2B9c"
