[universal.address]
Dictatorship = "0x397CA6373D46a15510Ce3045d09b7cbB3Af68EAa"
Position = "0x49F7e5F896ad4530eBedB1d4697Ffb5b31f34972"
Registry = "0x0000000000000000000000000000000000000000"
MasterHook = "0x0bf4f1740E9809b88c9B0317654EB80c35CEe33E"
Withdraw = "0x4f87978d851D9D17B73D426A15A58CF9F064e16E"

[arbitrum.address]
TokenRouter = "0x0c69DB327925cd9367E39B7CB773Fcf97005a02c"
ProxyUserRouter = "0x8ea4425d1f26f1c715AF4020427480af9Fef20fF"
Match = "0xE7eAB5469ebbE492469E723FF5DAe7Cb91c6D04e"
Allocate = "0x5d2D41305b33DFf126FCb9585f919c7f13d183dB"
UserRouter = "0x91DeC0891d3d5DF935790C6dc97c674f7f976994"
GmxStage = "0xB5E7CC3eD87F4f517351D50C639Fe9aB22b1D2Eb"

[arbitrum.token]
USDC = "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"
USDT = "0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9"
DAI = "0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1"
WETH = "0x82aF49447D8a07e3bd95BD0d56f35241523fBab1"
WBTC = "0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f"

[base.token]
USDC = "0x833589fcd6edb6e08f4c7c32d4f71b54bda02913"
USDT = "0xfde4C96c8593536E31F229EA8f37b2ADa2699bb2"
DAI = "0x50c5725949A6F0c72E6C4a641F24049A917DB0Cb"
WETH = "0x4200000000000000000000000000000000000006"
WBTC = "0x0555E30da8f98308EdB960aa94C0Db47230d2B9c"
