[universal.address]
Dictatorship = "0x397CA6373D46a15510Ce3045d09b7cbB3Af68EAa"
Position = "0xcef479cf0C6A8855561554738fe7aC4f43d45756"
Registry = "0x2D28Ac8DE4c2b45e9252ef835929AAECbdF86141"
MasterHook = "0xBBE149F3B6D27FBc60c2e73D13375AAfA538eC30"
Withdraw = "0x4f87978d851D9D17B73D426A15A58CF9F064e16E"
MasterRouter = "0xD2e09A9b0C6bd10e07f2874B9fd479E7B5Ff2f13"

[arbitrum.address]
"__MasterRouter" = "0x6D4E960E4b08A4A144ee269417C2F827b08b788e"
TokenRouter = "0x418aE8cc6628E7921aF2c6f6526d5f54537670bb"
ProxyUserRouter = "0x0a4f9244C67F743A590599226A180b76af2829De"
Match = "0x403124Bfa8E795E82b1976B06D7a453BFcff1A7B"
Allocate = "0xA53fAc1423A35185bd16af21FC1De1f288a3Fa7A"
UserRouter = "0x18C48Cd6f71E17dA86F7b375fEB44678188679e7"
GmxStage = "0x0679bD70463EfC2b31A3914C483d3083004dBE27"
